import type { Metadata } from 'next'
import LegalDocument from '@/components/legal/LegalDocument'

export const metadata: Metadata = { title: 'Terms of Use' }

export default function TermsPage() {
  return <LegalDocument eyebrow="TERMS" title="The rules, in plain English." summary="These terms cover The Relo Network website, The London Brief and Ask Relo. Paid work also has its own proposal or order terms, which you will see before agreeing to anything." updated="27 August 2026" sections={[
    { title: 'About these terms', paragraphs: ['Relo Network Ltd operates this website from London, United Kingdom. By using the site, you agree to these terms. If you buy a service, the proposal or order terms for that work take priority if there is a conflict.'] },
    { title: 'General information, not professional advice', paragraphs: ['Our articles and Ask Relo provide general information. They are not legal, immigration, tax, financial, medical, surveying or school admissions advice. Rules, prices and availability change. Check important decisions with the relevant official body or qualified professional.'] },
    { title: 'Ask Relo beta', bullets: ['Answers may be incomplete, out of date or wrong. Do not rely on them alone for an important decision.', 'Do not submit passwords, payment details, passport numbers, medical records or confidential information about someone else.', 'We limit free questions to keep the service available and prevent abuse.', 'Voice is unavailable unless the website clearly shows that it is enabled.'] },
    { title: 'Relocation enquiries and paid work', paragraphs: ['Sending a relocation brief does not create a contract, and the form does not take payment. We review your brief before suggesting a call or service. Paid work begins only after we agree what we will do, the price, the timing, each person’s responsibilities and any cancellation terms. We cannot guarantee a property, tenancy, visa, school place, supplier or decision made by someone else.'] },
    { title: 'Your cancellation rights', paragraphs: ['If UK consumer cancellation rights apply, we will give you the required information and explain how to cancel before you buy. If you ask us to start during a legal cancellation period, the order terms will explain what that means. These terms do not remove rights that the law says you must keep.'] },
    { title: 'Advertising and sponsored work', paragraphs: ['Partners pay for specific articles or placements. They do not buy client introductions, positive coverage or priority in Ask Relo recommendations. We label sponsored work and agree its content, timing, cancellation terms, rights and reporting separately.'] },
    { title: 'Acceptable use', bullets: ['Do not interfere with the service, attempt unauthorised access or evade usage limits.', 'Do not submit unlawful, abusive, misleading or infringing material.', 'Do not scrape, reproduce or commercially exploit substantial website content without permission.', 'You are responsible for having authority to provide information about another person.'] },
    { title: 'Our content and external links', paragraphs: ['Our original branding, articles and website materials are protected by law. You may use them for personal purposes, but not copy or sell substantial parts without permission. A link or named organisation does not mean we endorse it unless we clearly say so.'] },
    { title: 'Availability and responsibility', paragraphs: ['We try to keep the site available but cannot promise uninterrupted access. Where the law allows, we are not responsible for indirect loss caused by relying on free articles or beta content. The terms for paid work explain responsibility for that service.'] },
    { title: 'Changes and contact', paragraphs: ['We may update these terms when the service changes. Material changes apply from the stated update date. Questions may be sent to hello@therelonetwork.com. These terms are governed by the laws of England and Wales, subject to any mandatory consumer protections.'] },
  ]} />
}
