import type { Metadata } from 'next'
import LegalDocument from '@/components/legal/LegalDocument'

export const metadata: Metadata = { title: 'Terms of Use' }

export default function TermsPage() {
  return <LegalDocument eyebrow="TERMS" title="Clear terms for considered decisions." summary="These website terms govern use of The Relo Network, The London Brief and Ask Relo. Paid relocation work and editorial campaigns are also governed by the proposal or order terms accepted for that engagement." updated="26 August 2026" sections={[
    { title: 'About these terms', paragraphs: ['The website is operated by Relo Network Ltd in London, United Kingdom. By using it, you agree to these terms. If you enter a paid engagement, the signed proposal, statement of work or order terms take priority if there is a conflict.'] },
    { title: 'Information, not professional advice', paragraphs: ['Editorial content and Ask Relo provide general decision support. They are not legal, immigration, tax, financial, medical, surveying or school-admissions advice. Rules, prices and availability change; verify important decisions with the relevant official body or qualified professional.'] },
    { title: 'Ask Relo beta', bullets: ['Answers may be incomplete, outdated or wrong and should not be the sole basis for a consequential decision.', 'Do not submit passwords, payment details, passport numbers, medical records or confidential third-party information.', 'Complimentary usage limits may be enforced to protect availability and prevent abuse.', 'Voice functionality is unavailable unless expressly shown as enabled.'] },
    { title: 'Relocation enquiries and contracts', paragraphs: ['Submitting a brief does not create a contract and no payment is taken through the qualification form. We review fit before recommending a call, proposal or service. A paid engagement begins only after scope, price, timing, responsibilities and applicable cancellation terms are agreed. We do not guarantee a property, tenancy, visa, school place, supplier availability or any decision controlled by a third party.'] },
    { title: 'Consumer cancellation rights', paragraphs: ['Where UK consumer cancellation rights apply to a distance contract, the relevant pre-contract information and cancellation procedure will be provided before purchase. If you ask us to begin a service during a statutory cancellation period, the order terms will explain the effect of that request. Nothing in these terms limits rights that cannot lawfully be excluded.'] },
    { title: 'Partner and sponsored activity', paragraphs: ['Advertising purchases defined media inventory only. They do not purchase client introductions, positive coverage or priority in independent Ask Relo recommendations. Sponsored material is labelled, and campaign scope, delivery, cancellation, intellectual-property rights and reporting are agreed separately.'] },
    { title: 'Acceptable use', bullets: ['Do not interfere with the service, attempt unauthorised access or evade usage limits.', 'Do not submit unlawful, abusive, misleading or infringing material.', 'Do not scrape, reproduce or commercially exploit substantial website content without permission.', 'You are responsible for having authority to provide information about another person.'] },
    { title: 'Intellectual property and links', paragraphs: ['The Relo Network’s original branding, editorial work and site materials are protected by applicable rights. Limited personal use is permitted. External links and named organisations are provided for context and do not imply endorsement unless expressly stated.'] },
    { title: 'Availability and liability', paragraphs: ['We aim to keep the site available but do not promise uninterrupted access. To the extent permitted by law, we are not responsible for indirect loss arising from reliance on free editorial or beta content. Liability for paid work is governed by the applicable engagement terms.'] },
    { title: 'Changes and contact', paragraphs: ['We may update these terms when the service changes. Material changes apply from the stated update date. Questions may be sent to hello@therelonetwork.com. These terms are governed by the laws of England and Wales, subject to any mandatory consumer protections.'] },
  ]} />
}
